### PR TITLE
Move to Gradle dependencies

### PR DESCRIPTION
**Pull request by nolith**
I propose that you move to Gradle based dependency rather than a dependent
plugin. When you link in the other plugin it may cause multiple dexing issues
with other plugins.

### CODE REVIEW

**Comment by alexanderwallin** [comment]
I agree, `<framework />` is the way to go. However, to prevent Play Services 9.x to break the plugin the lib version should be set to `8.+`.

**Comment by neekfenwick** [comment]
What's going on here guys?  Our project is experiencing serious pain because of the inability to have phonegap-plugin-push and this analytics plugin installed at the same time.  See https://groups.google.com/forum/#!topic/phonegap/u_KG7_M4IJg for my discussion and the phonegap-plugin-push author's feedback.

**Comment by polyn0m** [comment]
+1, this pull request must be merged!

If use [cordova-plugin-crosswalk-webview](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) without this fix, build throw error:

> :transformClassesWithDexForArmv7Debug
> UNEXPECTED TOP-LEVEL EXCEPTION:
> com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
>         at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:484)
>         at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:261)
>         at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:473)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:161)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
>         at com.android.dx.command.dexer.Main.run(Main.java:277)
>         at com.android.dx.command.dexer.Main.main(Main.java:245)
>         at com.android.dx.command.Main.main(Main.java:106)
> 
>  FAILED
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':transformClassesWithDexForArmv7Debug'.
>   
>   > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

I use this fix and problem solved!

**Comment by alexanderwallin** [comment]
This has already been resolved, no?

https://github.com/appfeel/analytics-google/commit/429adea5bab769872fabc1883b8ea5fc3f49f30f

**Comment by polyn0m** [comment]
@alexanderwallin if you use [cordova-plugin-crosswalk-webview](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview), like me, you get error when build APK, otherwise [429adea](https://github.com/appfeel/analytics-google/commit/429adea5bab769872fabc1883b8ea5fc3f49f30f) fix problem.

I think [d9dba33](https://github.com/appfeel/analytics-google/pull/11/commits/d9dba33cf64a46498caf5d07db9a9e830898312c) a better solution, because it's work always.

**Comment by miqmago** [comment]
Please, could you fix it with the newest HEAD?
As there has been some work after your commit, it's not possible to merge it.
Thanks!

**Comment by polyn0m** [comment]
@miqmago this one [c6aa831](https://github.com/polyn0m/analytics-google/commit/c6aa831b6df6d0f5757e8081d08a97047603138b)? Create pull request?

**Comment by miqmago** [comment]
That's it, can you create a PR from that repo pls?

**Pull request merged**
